# SPDX-FileCopyrightText: 2023 Vera Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Zoldorf <silvertorch5@gmail.com>
# SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 DrSmugleaf <10968691+DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 LankLTE <135308300+LankLTE@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 TurboTracker <130304754+TurboTrackerss14@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 nikthechampiongr <32041239+nikthechampiongr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 to4no_fix <156101927+chavonadelal@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Myra <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2025 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2025 crazybrain23 <44417085+crazybrain23@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Base configuration preset used on all Wizard's Den servers.
# Loaded before server-specific config presets by configuration.

[game]
desc             = "Мёртвый Космос Goob — русскоязычный сервер Space Station 14 на сборке GoobStation."
lobbyenabled     = true
soft_max_players = 80
lobbyduration    = 300 # 5 minutes lobby timer
panic_bunker.enabled = false
panic_bunker.min_overall_minutes = 0
panic_bunker.disable_with_admins = false
panic_bunker.enable_without_admins = false
panic_bunker.show_reason = true
panic_bunker.custom_reason = ""

# IPIntel stuff
ipintel_enabled = false
ipintel_contact_email = ""
ipintel_bad_rating = 0.99
ipintel_alert_admin_warn_rating = 0.95

[infolinks]
bug_report = "https://discord.gg/ds14"
discord    = "https://discord.gg/ds14"
forum      = ""
github     = ""
patreon    = ""
website    = "https://deadspace14.net/"
wiki       = "https://wiki.deadspace14.net/"
appeal     = "https://discord.gg/ds14"

[server]
rules_file = "StandardRuleset"

[movement]
mob_pushing = true

[net]
max_connections = 1024

[vote]
restart_required_ratio = 0.7

[netres]
limit = 10.0

[admin]
see_own_notes = true
deadmin_on_join = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2
allow_multi_server_play = false

[atmos]
max_explosion_range = 10

[status]
privacy_policy_link = ""
privacy_policy_identifier = "deadspace"
privacy_policy_version = "2026-06-09"
